[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/golang-lru"

[[constraint]]
  branch = "master"
  name = "github.com/kardianos/osext"

[[constraint]]
  branch = "master"
  name = "github.com/puma/puma-dev"

[[constraint]]
  branch = "master"
  name = "github.com/vektra/errors"

[[constraint]]
  branch = "master"
  name = "github.com/yhat/wsutil"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"
